/*
//Author      : 6R347-0BL1V10N
//date        : August 9, 2018
//purpose     : ProjectEuler.net - Problem 2

//description : Each new term in the Fibonacci sequence
//				is generated by adding the previous two terms.
//				By starting with 1 and 2, the first 10 terms will be:
//				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//				By considering the terms in the Fibonacci sequence
//				whose values do not exceed four million,
//				find the sum of the even-valued terms.
//
*/
#include <iostream>

int main()
{

	int sum = 0; //sum of all even numbers
	int x = 0; 
	int y = 1;
	int z = 0;

	while (z < 4000000)
	{
		z = x + y; 
		if (z % 2 == 0)
		{
			sum += z;
		}
		x = y;
		y = z;
	}
	std::cout << sum << std::endl;
	std::cin.get();

	return 1; //standard main exit #
}

/*
// output : 4613732
*/
